esphome:
  name: garage-door

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  manual_ip:
    static_ip: 192.168.30.140
    gateway: 192.168.30.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Door Fallback Hotspot"
    password: "ifcrw22WuC7O"

captive_portal:

sensor:
  - platform: wifi_signal
    name: "Garage Door Wifi"
    update_interval: 60s
    unit_of_measurement: "%"
    filters:
      - lambda: |-
          if (x <= -100) {
            return 0;
          } else {
            if (x >= -50) {
              return 100;
            } else {
              return 2 * (x + 100);
            }
          }
  - platform: ultrasonic
    trigger_pin: D6
    echo_pin: D5
    id: garage_door_sensor
    update_interval: 1s
    timeout: 3.5m
    pulse_time: 15us
    internal: true
    filters:
      - filter_out: nan
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1
          send_first_at: 1

cover:
  - platform: template
    name: Garage Door
    icon: "mdi:garage"
    lambda: !lambda |-
      if (id(garage_door_sensor).state > 1.0) {
        return COVER_CLOSED;
      } else {
        return COVER_OPEN;
      }

output:
  - platform: gpio
    pin: D7
    id: relay

button:
  - platform: output
    name: "Garage Door Remote"
    output: relay
    duration: 500ms
    icon: "mdi:remote"
