esphome:
  name: garage-door

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Optional manual IP
  manual_ip:
    static_ip: 192.168.30.140
    gateway: 192.168.30.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garage-Door Fallback Hotspot"
    password: "ifcrw22WuC7O"

captive_portal:

sensor:
  - platform: ultrasonic
    trigger_pin: D6
    echo_pin: D5
    id: garage_door_sensor
    update_interval: 2s
    timeout: 3m
    pulse_time: 15us
    internal: true

cover:
  - platform: template
    name: Garage Door
    icon: "mdi:garage"
    lambda: !lambda |-
      if (id(garage_door_sensor).state > 1.0) {
        return COVER_CLOSED;
      } else {
        return COVER_OPEN;
      }

output:
  - platform: gpio
    pin: D7
    id: relay

button:
  - platform: output
    name: "Garage Door Remote"
    output: relay
    duration: 500ms
    icon: "mdi:remote"
